chore: test github script

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -11,96 +11,110 @@ jobs:
     test:
         runs-on: ubuntu-latest
         container: docker:27-cli
-        services:
-            docker:
-                image: docker:27-dind
-                options: --privileged
-        env:
-            DOCKER_HOST: tcp://docker:2375
-            DOCKER_TLS_CERTDIR: ''
-        steps:
-            - uses: actions/checkout@v4
-            - run: docker info
-            - run: docker ps -a
 
-    ci:
-        runs-on: ubuntu-24.04-arm
-        container:
-            image: node:24-bookworm
-            options: --add-host=host.docker.internal:127.0.0.1
         services:
             docker:
                 image: docker:27-dind
-                options: --privileged
-        env:
-            DOCKER_HOST: tcp://docker:2375
-            DOCKER_TLS_CERTDIR: ''
-            DOCKER_BUILDKIT: 1
-            WORKSPACE_ROOT: ${{ github.workspace }}
-            TERM: xterm
+                options: >-
+                    --privileged
+                    --health-cmd "docker info"
+                    --health-interval 5s
+                    --health-timeout 3s
+                    --health-retries 20
 
         steps:
             - uses: actions/checkout@v4
 
-            - name: Install Tools
-              run: apt-get update && apt-get install -y curl jq iproute2
+            - name: docker info
+              run: docker info
+              env:
+                  DOCKER_HOST: tcp://docker:2375
+                  DOCKER_TLS_CERTDIR: ''
 
-            - name: Install Docker
-              run: |
-                  apt-get install -y ca-certificates curl gnupg
-                  install -m 0755 -d /etc/apt/keyrings
-                  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
-                  chmod a+r /etc/apt/keyrings/docker.gpg
-                  echo \
-                    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
-                    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
-                    tee /etc/apt/sources.list.d/docker.list > /dev/null
-                  apt-get update
-                  apt-get install -y docker-ce-cli
+            - name: docker ps
+              run: docker ps -a
+              env:
+                  DOCKER_HOST: tcp://docker:2375
+                  DOCKER_TLS_CERTDIR: ''
 
-            - name: Install Dependencies
-              run: npm ci
+        # ci:
+        #     runs-on: ubuntu-24.04-arm
+        #     container:
+        #         image: node:24-bookworm
+        #         options: --add-host=host.docker.internal:127.0.0.1
+        #     services:
+        #         docker:
+        #             image: docker:27-dind
+        #             options: --privileged
+        #     env:
+        #         DOCKER_HOST: tcp://docker:2375
+        #         DOCKER_TLS_CERTDIR: ''
+        #         DOCKER_BUILDKIT: 1
+        #         WORKSPACE_ROOT: ${{ github.workspace }}
+        #         TERM: xterm
 
-            # - name: Lint
-            #   run: npm run lint
+        #     steps:
+        #         - uses: actions/checkout@v4
 
-            - name: Run infrastructures
-              run: npm run infra:reset
+        #         - name: Install Tools
+        #           run: apt-get update && apt-get install -y curl jq iproute2
 
-            - name: TEST
-              run: |
-                  docker ps -a
-                  curl -v 127.0.0.1:27017
-                  curl -v host.docker.internal:27017
+        #         - name: Install Docker
+        #           run: |
+        #               apt-get install -y ca-certificates curl gnupg
+        #               install -m 0755 -d /etc/apt/keyrings
+        #               curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
+        #               chmod a+r /etc/apt/keyrings/docker.gpg
+        #               echo \
+        #                 "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
+        #                 $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
+        #                 tee /etc/apt/sources.list.d/docker.list > /dev/null
+        #               apt-get update
+        #               apt-get install -y docker-ce-cli
 
-            - name: Run unit tests
-              run: npm test
+        #         - name: Install Dependencies
+        #           run: npm ci
 
-            - name: Run e2e tests
-              run: npm run test:e2e
+        #         # - name: Lint
+        #         #   run: npm run lint
 
-            - name: Dump Docker logs on failure
-              if: ${{ failure() }}
-              continue-on-error: true
-              run: |
-                  docker ps -a || true
+        #         - name: Run infrastructures
+        #           run: npm run infra:reset
 
-                  for id in $(docker ps -aq); do
-                    echo ""
-                    echo "========================= $id ========================="
-                    docker logs --timestamps --tail 300 "$id" || true
-                  done
+        #         - name: TEST
+        #           run: |
+        #               docker ps -a
+        #               curl -v 127.0.0.1:27017
+        #               curl -v host.docker.internal:27017
 
-            # - name: Setup Network
-            #   run: |
-            #       echo "127.0.0.1 host.docker.internal" | tee -a /etc/hosts
+        #         - name: Run unit tests
+        #           run: npm test
 
-            # - name: Run e2e tests (x100)
-            #   run: |
-            #       set -e
-            #       for i in $(seq 1 100); do
-            #         echo "[Run $i/100]"
-            #         docker ps -a
-            #         npm run infra:gui
-            #       done
-            #       echo "Done. 100 run(s) finished."
+        #         - name: Run e2e tests
+        #           run: npm run test:e2e
+
+        #         - name: Dump Docker logs on failure
+        #           if: ${{ failure() }}
+        #           continue-on-error: true
+        #           run: |
+        #               docker ps -a || true
+
+        #               for id in $(docker ps -aq); do
+        #                 echo ""
+        #                 echo "========================= $id ========================="
+        #                 docker logs --timestamps --tail 300 "$id" || true
+        #               done
+
+        #         # - name: Setup Network
+        #         #   run: |
+        #         #       echo "127.0.0.1 host.docker.internal" | tee -a /etc/hosts
+
+        #         # - name: Run e2e tests (x100)
+        #         #   run: |
+        #         #       set -e
+        #         #       for i in $(seq 1 100); do
+        #         #         echo "[Run $i/100]"
+        #         #         docker ps -a
+        #         #         npm run infra:gui
+        #         #       done
+        #         #       echo "Done. 100 run(s) finished."
